/**
 * Radius Monitor Add Profile
 * Made by Maizil <https://github.com/maizil41>
 */
document.addEventListener('DOMContentLoaded',function(){document.getElementById("addUserForm").addEventListener("submit",function(event){var messageElement=document.getElementById("message");if(messageElement){messageElement.style.display="none"}
if(this.checkValidity()){document.getElementById("loader").style.display="inline-block"}else{event.preventDefault()}});fetch('../backend/bandwidth.php').then(response=>response.json()).then(data=>{let bwDropdown=document.getElementById('bw_id');if(Array.isArray(data.data)){data.data.forEach(item=>{let option=document.createElement('option');option.value=item.bw_id;option.textContent=item.bw_name;bwDropdown.appendChild(option)});bwDropdown.addEventListener('change',function(){let selectedBw=bwDropdown.value;let selectedItem=data.data.find(item=>item.bw_id===selectedBw);if(selectedItem){document.getElementById('rate_down').value=selectedItem.rate_down||'';document.getElementById('rate_up').value=selectedItem.rate_up||''}})}});function updateLimitType(){let limitType=document.getElementById("Type").value;let timeLimit=document.getElementById("TimeLimit");let validityLimit=document.getElementById("ValidityLimit");let dataLimit=document.getElementById("DataLimit");timeLimit.style.display="none";validityLimit.style.display="none";dataLimit.style.display="none";if(limitType==="Time_Limit"){timeLimit.style.display="table-row";validityLimit.style.display="table-row"}else if(limitType==="Data_Limit"){dataLimit.style.display="table-row"}else if(limitType==="Both_Limit"){timeLimit.style.display="table-row";validityLimit.style.display="table-row";dataLimit.style.display="table-row"}}
document.getElementById("Type").addEventListener("change",updateLimitType);updateLimitType();function handlePlanTypeChange(){var planType=document.querySelector('input[name="typebp"]:checked');if(!planType)return;var planTypeValue=planType.value;var limitTypeSection=document.getElementById('Type');var timeLimitSection=document.getElementById('TimeLimit');var dataLimitSection=document.getElementById('DataLimit');if(planTypeValue==='Limited'){limitTypeSection.style.display='block';var limitType=document.querySelector('input[name="limit_type"]:checked');if(!limitType)return;var limitTypeValue=limitType.value;if(limitTypeValue==='Time_Limit'){timeLimitSection.style.display='block';dataLimitSection.style.display='none'}else if(limitTypeValue==='Data_Limit'){timeLimitSection.style.display='none';dataLimitSection.style.display='block'}else if(limitTypeValue==='Both_Limit'){timeLimitSection.style.display='block';dataLimitSection.style.display='block'}}else{limitTypeSection.style.display='none';timeLimitSection.style.display='none';dataLimitSection.style.display='none'}}
document.querySelectorAll('input[name="typebp"]').forEach(function(radio){radio.addEventListener('change',handlePlanTypeChange)});document.querySelectorAll('input[name="limit_type"]').forEach(function(radio){radio.addEventListener('change',handlePlanTypeChange)});handlePlanTypeChange();document.getElementById('planTimeBankInput').addEventListener('input',calculatePlanBank);document.getElementById('planTimeBankSelect').addEventListener('change',calculatePlanBank);document.getElementById('profileTimeBankInput').addEventListener('input',calculateProfileBank);document.getElementById('profileTimeBankSelect').addEventListener('change',calculateProfileBank);document.getElementById('data_limit').addEventListener('input',calculateDataLimit);document.getElementById('data_unit').addEventListener('change',calculateDataLimit);function calculatePlanBank(){let timeValue=parseFloat(document.getElementById('planTimeBankInput').value);let timeUnit=document.getElementById('planTimeBankSelect').value;let convertedValue;if(isNaN(timeValue))return;if(timeUnit==="M")convertedValue=timeValue*60;else if(timeUnit==="H")convertedValue=timeValue*3600;else if(timeUnit==="D")convertedValue=timeValue*86400;document.getElementById('planTimeBank').value=convertedValue}
function calculateProfileBank(){let timeValue=parseFloat(document.getElementById('profileTimeBankInput').value);let timeUnit=document.getElementById('profileTimeBankSelect').value;let convertedValue;if(isNaN(timeValue))return;if(timeUnit==="M")convertedValue=timeValue*60;else if(timeUnit==="H")convertedValue=timeValue*3600;else if(timeUnit==="D")convertedValue=timeValue*86400;document.getElementById('profileTimeBank').value=convertedValue}
function calculateDataLimit(){let dataValue=parseFloat(document.getElementById('data_limit').value);let dataUnit=document.getElementById('data_unit').value;let convertedValue;if(isNaN(dataValue))return;if(dataUnit==="MB")convertedValue=dataValue*1048576;else if(dataUnit==="GB")convertedValue=dataValue*1073741824;document.getElementById('dataLimit').value=convertedValue}})